name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-Zthreads=3 -Zmacro-backtrace -Ctarget-cpu=native'

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: default to nightly Rust
      run: |
        rustup update nightly
        rustup default nightly
        rustup component add rustfmt clippy
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: run fmt and clippy check
      run: cargo fmt -- --check; cargo clippy -- -D warnings
